language: python

python:
  - 3.7

install:
  - pip install behave
  - pip install poetry

before_script:
  - poetry config repositories.testpypi https://test.pypi.org/legacy/
  - poetry config http-basic.testpypi "${TESTPYPI_USERNAME}" "{$TESTPYPI_PASSWORD}"

script:
  - python -m unittest discover
  - behave

deploy:
  - provider: script
    skip_cleanup: true
    script: poetry publish -r testpypi --username=$TESTPYPI_USERNAME --password=$TESTPYPI_PASSWORD
