language: python

python:
  - 3.7

install:
  - pip install behave
  - pip install poetry
  - pip install black
  - pip install flake8

before_script:
  - poetry config repositories.testpypi https://test.pypi.org/legacy/

script:
  - black
  - flake8
  - python -m unittest discover
  - behave
  - poetry build

deploy:
  - provider: script
    skip_cleanup: true
    script: poetry publish --repository testpypi --username=$TESTPYPI_USERNAME --password=$TESTPYPI_PASSWORD
    on:
      branch: master
